# Generated by Django 4.2.13 on 2024-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockendrule',
            name='stable_lookback_pattern',
            field=models.BooleanField(default=False, verbose_name='Trigger if the same choices have been made for 80% of previous 20 cycles'),
        ),
        migrations.AlterField(
            model_name='blockendrule',
            name='stable_lookback_points',
            field=models.BooleanField(default=False, verbose_name='Trigger if the same player has had the most points for 80% of previous 20 cycles'),
        ),
        migrations.AlterField(
            model_name='comborulemodification',
            name='new_schedule_number',
            field=models.CharField(blank=True, max_length=10, verbose_name="New schedule number - leave blank if not changed, supports '+:5' or '-:5'"),
        ),
        migrations.AlterField(
            model_name='singlerulemodification',
            name='new_schedule_number',
            field=models.CharField(blank=True, max_length=10, verbose_name="New schedule number - leave blank if not changed, supports '+:5' or '-:5'"),
        ),
    ]
