# Generated by Django 4.2.13 on 2024-07-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyoapp', '0003_alter_blockendrule_options_blockendrule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlerule',
            name='mutable_rule',
        ),
        migrations.AlterField(
            model_name='blockendrule',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockendrule_set', to='kyoapp.block'),
        ),
        migrations.AlterField(
            model_name='blockendrule',
            name='min_cycles',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name="Minimum number of cycles before checking, if greater than condition's minimum cycles"),
        ),
        migrations.AlterField(
            model_name='singlerule',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyoapp.block', verbose_name='Condition'),
        ),
    ]
