# Generated by Django 5.0.7 on 2024-08-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyoapp', '0005_block_allowed_groups_block_allowed_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_message', models.TextField(blank=True)),
                ('decrease_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='feedback_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyoapp.feedbackmodule'),
        ),
        migrations.AddField(
            model_name='comborule',
            name='feedback_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyoapp.feedbackmodule'),
        ),
        migrations.AddField(
            model_name='game',
            name='feedback_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyoapp.feedbackmodule'),
        ),
        migrations.AddField(
            model_name='singlerule',
            name='feedback_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyoapp.feedbackmodule'),
        ),
    ]
